import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "NextBlog | Blog Post Platform",
  description: "NextBlog is generated by Mohammed Abdullah",
  icons: {
    icon: "/favicon.png", // Path from public folder
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Navbar />
          <div className="min-h-screen">{children}</div>
        </div>
      </body>
    </html>
  );
}
